### PR TITLE
Plasma Mobile support

### PR DESCRIPTION
**Pull request by Danct12**
This pull request adds support for Plasma Mobile. Cannot test it any further as my SD card decided to kill itself after I ran pacman -Syu on it, but it does boot and work fine.

### CODE REVIEW

**Comment by PoorPocketsMcNewHold** [comment]
Tested on my Pinephone, with a direct eMMC write. Worked great. Encrypted drive, boot-up unlock keyboard and prompt, and the system booting after that. Everything went well.
Flashed from an Arch Linux install.
```
[20:38][~/Downloads]-> sudo ./installer.sh 
Which image do you want to create?
1) PinePhone
2) PineTab
#? 1
Which environment would you like to install?
1) Phosh
2) Plasma
3) Barebone
#? 2
Which filesystem would you like to use?
1) ext4
2) f2fs
#? 1
Which SD card do you want to flash?
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 232,9G  0 disk 
└─sda1        8:1    0 232,9G  0 part /run/media/pm/Ventilateur
sdb           8:16   0   1,8T  0 disk 
└─sdb1        8:17   0   1,8T  0 part 
sdc           8:32   0   1,8T  0 disk 
└─sdc1        8:33   0   1,8T  0 part 
sdd           8:48   0 596,2G  0 disk 
└─sdd1        8:49   0 596,2G  0 part 
sde           8:64   0 931,5G  0 disk 
├─sde1        8:65   0 836,5G  0 part 
├─sde2        8:66   0   513M  0 part /boot/efi
└─sde3        8:67   0  94,5G  0 part /
sdf           8:80   1  14,7G  0 disk 
sdg           8:96   1  59,7G  0 disk 
└─sdg1        8:97   1    49M  0 part 
sdh           8:112  1   125G  0 disk 
└─sdh1        8:113  1   125G  0 part /run/media/pm/C000-00BB
sr0          11:0    1  1024M  0 rom  
nvme0n1     259:0    0 465,8G  0 disk 
├─nvme0n1p1 259:1    0   100M  0 part 
├─nvme0n1p2 259:2    0    16M  0 part 
├─nvme0n1p3 259:3    0 465,1G  0 part 
└─nvme0n1p4 259:4    0   512M  0 part 
Device node (/dev/sdX): /dev/sdf
Flashing image to: /dev/sdf
WARNING: All data will be erased! You have been warned!
Some commands require root permissions, you might be asked to enter your sudo password.

ARE YOU SURE /dev/sdf IS WHAT YOU PICKED?
Confirm device node: /dev/sdf

Downloading images...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    281      0 --:--:-- --:--:-- --:--:--   280
archlinux-pinephone-plasma.sqfs: Réussi
arch-install-scripts.tar.zst  100%[=================================================>]  14,21K  --.-KB/s    ds 0s      
You'll now be asked to type in a new encryption key. DO NOT LOSE THIS!
Saisissez la phrase secrète pour /dev/sdf2 : 
Vérifiez la phrase secrète : 
ATTENTION: Le répertoire verrou /run/cryptsetup est manquant !
Emplacement de clef 0 créé.
Opération réussie.
Saisissez la phrase secrète pour /dev/sdf2 : 
mkfs.fat 4.2 (2021-01-31)
mke2fs 1.46.2 (28-Feb-2021)
En train de créer un système de fichiers avec 3781632 4k blocs et 946560 i-noeuds.
UUID de système de fichiers=6aca9fdc-1ab0-4e08-a47d-92bcde1db1e6
Superblocs de secours stockés sur les blocs : 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

Allocation des tables de groupe : complété                        
Écriture des tables d'i-noeuds : complété                        
Création du journal (16384 blocs) : complété
Écriture des superblocs et de l'information de comptabilité du système de
fichiers : complété

Parallel unsquashfs: Using 12 processors
133664 inodes (152824 blocks) to write

[=================================================================================================/] 152824/152824 100%

created 114217 files
created 7708 directories
created 17530 symlinks
created 0 devices
created 0 fifos
created 0 sockets
UUID=6aca9fdc-1ab0-4e08-a47d-92bcde1db1e6	/         	ext4      	rw,relatime	0 1
UUID=1E66-82E6      	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro	0 2
90+1 enregistrements lus
90+1 enregistrements écrits
739148 octets (739 kB, 722 KiB) copiés, 0,0121196 s, 61,0 MB/s

Cleaning up working directory...
All done! Please insert the card to your device and power on.
```

image

**Comment by adocampo** [comment]
Installing it to eMMC via jumpdrive. It works, but is a bit annoying during the process (even just downloading the image) plasma notifies about connections and disconnections of the phone so network and disk notifications are spawning multiple times (and as I have multiple monitors, it seems a party)

https://user-images.githubusercontent.com/2266612/112828572-2aa3cb80-9090-11eb-804e-12cbd94cd24b.mp4

Now testing Plasma, good work!!

**Comment by Danct12** [comment]
Please try another cable, and make sure the phone is charged to at least 70%.

**Comment by adocampo** [comment]
The cable is the official one, and I do all the test with it, and it's the very first time it happens, I will try with another flashing just to discard it has broken just now.
But it's true the phone was at 20% or so... I will charge it and re-flash

**Comment by adocampo** [comment]
I've tried again to re-flash with a fully charged phone (well, you know, at 89% which is the maximum pinephone can charge) and with the same cable on the same usb port, no notification party this time.

I would like to know if there is a way to avoid fs encryption, I would like to have it once the device will be ready as a daily driver, but now we are doing tests and rebooting now and then, I found it annoying.

**Pull request merged**
